# PRIVATE REGISTRY LINT WORKFLOW
# ===============================
# This workflow requires authentication for the GitHub private registry.
# All @openzeppelin packages (including dependencies) are resolved from the private registry
# due to organization-level scoping in .npmrc.

name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Configure npm authentication for private registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Lint check
        run: pnpm lint

      - name: Debug global.css formatting
        run: |
          echo "=== Checking global.css file ==="
          echo "File info:"
          file packages/styles/global.css || echo "file command not found"
          echo ""
          echo "Last 5 lines with special characters visible:"
          cat -A packages/styles/global.css | tail -5
          echo ""
          echo "Prettier version:"
          cd packages/styles && npx prettier --version && cd ../..
          echo ""
          echo "Running prettier write to see if it changes anything:"
          cd packages/styles && npx prettier --write global.css --config ../../.prettierrc && cd ../..
          echo ""
          echo "Git diff after prettier write:"
          git diff packages/styles/global.css || echo "No changes detected"
          echo ""
          echo "Git status:"
          git status packages/styles/global.css || echo "Status check failed"
          echo ""
          echo "Running prettier check with debug info:"
          cd packages/styles && npx prettier --check global.css --config ../../.prettierrc --log-level debug && cd ../.. || echo "Check failed"
          echo ""
          echo "File size and permissions:"
          ls -la packages/styles/global.css
          echo ""
          echo "MD5 checksum:"
          md5sum packages/styles/global.css || shasum packages/styles/global.css || echo "Checksum failed"

      - name: Format check
        run: pnpm format:check

      - name: Adapter pattern compliance check
        run: pnpm lint:adapters
