# PRIVATE REGISTRY DEPENDENCY UPDATE WORKFLOW
# ===========================================
# This workflow requires authentication for the GitHub private registry.
# All @openzeppelin packages (including dependencies) are resolved from the private registry
# due to organization-level scoping in .npmrc.

name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  workflow_dispatch: # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.9.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Configure npm authentication for private registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Check for outdated dependencies
        id: outdated
        run: |
          echo "OUTDATED_DEPS=$(pnpm outdated --format json)" >> $GITHUB_ENV
        continue-on-error: true

      - name: Create PR for dependency updates
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates dependencies to their latest versions.

            <details>
            <summary>Outdated dependencies</summary>

            ```
            ${{ env.OUTDATED_DEPS }}
            ```
            </details>

            Auto-generated by the Update Dependencies workflow.
          branch: update-dependencies
          base: main
          labels: dependencies
